### ISSUE TITLE
Unable to parse recipe when `version_format` set to `[VER]` only.

### ISSUE THREAD

**Issue by TimothyDJones** [candrewlee14/webman-pkgs#5]
When creating a package recipe with `version_format` YAML attribute set to only `[VER]` (i.e., with no constant/literal value preceding it, such as "v"), the recipe fails to validate with error:
```
lf.yaml: unable to strict parse package recipe for lf: yaml: unmarshal errors:
  line 14: cannot unmarshal !!seq into string
```
Many GitHub projects use "raw" version number, so support for `[VER]` is important.

Note: I tried using `\[VER]`, which will validate, but it fails to work when executing the recipe due to regex error.

**Comment by candrewlee14** [comment]
That may be a YAML problem thinking that [VER] is a list. Try surrounding it in quotes like "[VER]".

Also, "[VER]" is the default for that field, so if you just delete that, it's assumed to be just a raw version number. That's why so many of the package configs don't include it.

**Comment by TimothyDJones** [comment]
Thanks for the reply. Makes perfect sense. I confirmed via update to the recipe that I had submitted for `pboy.yaml`. See new PR #6. Closing issue.
